#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "Running installers"

# find the installers and run them iteratively
echo "Installing homebrew ..."
sh -c ./homebrew/install.sh # Some other installs may need homebrew installed

find . -path ./homebrew -prune -false -o -name install.sh | while read installer ; do
	echo "Installing $(basename $(dirname $installer)) ..."
	sh -c "${installer}"
done

echo "Finished!"